#!/usr/bin/python3

#  Copyright 2024 Jelly Terra
#  Use of this source code form is governed under the MIT license.

import os
import subprocess
import sys
from os import getenv

cmdline = [
    'bwrap',
    '--unshare-user',
    '--unshare-pid',
    '--unshare-uts',
    '--unshare-cgroup',
    '--proc', '/proc',
    '--dev-bind', '/dev', '/dev',
    '--ro-bind-try', '/etc', '/etc',
    '--ro-bind-try', '/opt', '/opt',
    '--ro-bind-try', '/sys', '/sys',
    '--ro-bind-try', '/usr', '/usr',
    '--ro-bind-try', '/run/dbus', '/run/dbus',
    '--ro-bind-try', '/run/systemd', '/run/systemd',
    '--ro-bind-try', '/tmp/.X11-unix', '/tmp/.X11-unix',
    '--bind-try', '/data', '/data',
    '--bind-try', '/exdata', '/exdata',
    '--bind-try', '/tmp', '/tmp',
    '--symlink', '/usr/bin', '/bin',
    '--symlink', '/usr/lib', '/lib',
    '--symlink', '/usr/lib64', '/lib64',
]

COMMAND = ['bash']

if len(sys.argv) < 2:
    print(f'{sys.argv[0]} (name) [cmdline ...]')
    exit(1)

if len(sys.argv) > 2:
    COMMAND = sys.argv[2:]

HOME = getenv('HOME', '')
SPACE = getenv('SPACE', '')
if SPACE == '':
    print('$SPACE is undefined')
    exit(1)

SPACE_NAME = sys.argv[1]
SPACE_HOME = f'{SPACE}/home/{SPACE_NAME}'

cmdline += ['--bind-try', SPACE_HOME, SPACE_HOME]
cmdline += ['--bind-try', SPACE_HOME, HOME]

# D-Bus, Pipewire, X11, Wayland

XAUTH = getenv('XAUTHORITY', '')
if XAUTH != '':
    cmdline += ['--ro-bind-try', XAUTH, XAUTH]

XDG_RUNTIME_DIR = getenv('XDG_RUNTIME_DIR', '')
if XDG_RUNTIME_DIR != '':
    cmdline += ['--ro-bind-try', f'{XDG_RUNTIME_DIR}/bus', f'{XDG_RUNTIME_DIR}/bus']
    cmdline += ['--ro-bind-try', f'{XDG_RUNTIME_DIR}/pulse', f'{XDG_RUNTIME_DIR}/pulse']
    cmdline += ['--ro-bind-try', f'{XDG_RUNTIME_DIR}/pipewire-0', f'{XDG_RUNTIME_DIR}/pipewire-0']

    WAYLAND_DISPLAY = getenv('WAYLAND_DISPLAY', '')
    if WAYLAND_DISPLAY != '':
        cmdline += ['--ro-bind-try', f'{XDG_RUNTIME_DIR}/{WAYLAND_DISPLAY}', f'{XDG_RUNTIME_DIR}/{WAYLAND_DISPLAY}']

cmdline += COMMAND

env = os.environ
env['PS1'] = f'\\[\\e[${{PROMPT_COLOR:-33}}m\\]\\u@{SPACE_NAME}:\\[\\e[${{PROMPT_COLOR:-36}}m\\]\\w\\[\\e[0m\\]\\$ '

subprocess.run(cmdline, env=env)
